create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  case_id text not null,
  parent_id bigint references public.comments(id) on delete cascade,
  nickname text not null,
  tier text not null,
  content text not null,
  evidence text,
  vote text check (vote in ('A', 'B')),
  likes integer not null default 0 check (likes >= 0),
  created_at timestamptz not null default now()
);

create index if not exists comments_case_id_created_at_idx
  on public.comments (case_id, created_at desc);

create index if not exists comments_parent_id_idx
  on public.comments (parent_id);

alter table public.comments enable row level security;

grant select, insert on public.comments to anon;
grant select, insert on public.comments to authenticated;

drop policy if exists "comments are publicly readable" on public.comments;
create policy "comments are publicly readable"
  on public.comments
  for select
  to anon, authenticated
  using (true);

drop policy if exists "prototype users can create comments" on public.comments;
create policy "prototype users can create comments"
  on public.comments
  for insert
  to anon, authenticated
  with check (
    char_length(nickname) between 2 and 20
    and char_length(tier) between 1 and 40
    and char_length(content) between 1 and 2000
    and (evidence is null or char_length(evidence) <= 500)
  );

create or replace function public.increment_comment_likes(target_comment_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.comments
  set likes = likes + 1
  where id = target_comment_id;
$$;

revoke all on function public.increment_comment_likes(bigint) from public;
grant execute on function public.increment_comment_likes(bigint) to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'comments'
  ) then
    alter publication supabase_realtime add table public.comments;
  end if;
end;
$$;
